#!/usr/bin/env python3
# cli_memory_merchant.py
# CLI interactive port of your scenario. All narration and player lines kept verbatim.
# Merchant replies are generated by your LLM backend via /ai_response.
# Requires: requests (pip install requests)
#
# Behavior:
# - Press Enter to advance to the next dialogue line.
# - When a line contains multiple numbered choices (e.g. "1. ... 2. ..."), that whole line
#   is shown at once and the script asks you to type the number of your choice.
# - If a "P:" line is followed by several numbered option lines, that whole block is shown
#   at once and the script asks you to type a number.
# - The dialogue text is included exactly as provided by the user and is not altered,
#   except blank lines are skipped so you don't have to press Enter twice.
# - After you choose, the chosen option is displayed and the script advances immediately
#   (the numeric choice acts as the Enter) — only for choice blocks.

import requests, time, sys, re

SENTIMENT_URL = "http://localhost:8000/classify"
AI_URL = "http://localhost:8001/ai_response"
TIMEOUT = 15

state = {
    "mood": 0,
    "true_memories": 0,
    "false_memories": 0,
    "chapter": 1,
    "lost_fingers": 0,
    "history": []  # stores dicts: {player_text, sentiment, ai_text}
}

def call_sentiment(text):
    try:
        r = requests.post(SENTIMENT_URL, json={"text": text}, timeout=TIMEOUT)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        print(f"[!] Sentiment error: {e}")
        return None

def call_ai(text, sentiment=None, history=None):
    payload = {"text": text}
    if sentiment is not None:
        payload["sentiment"] = sentiment
    if history is not None:
        payload["history"] = history
    try:
        r = requests.post(AI_URL, json=payload, timeout=TIMEOUT)
        r.raise_for_status()
        return r.json()
    except Exception as e:
        print(f"[!] AI error: {e}")
        return None

def wait_for_advance():
    """
    Wait for user to press Enter (or type something then Enter).
    """
    try:
        input("(press Enter to continue) ")
    except EOFError:
        # In some environments EOF may happen; ignore to not crash.
        pass

def slow_print(lines, paging=True, delay=0.25):
    """
    Print lines one-by-one. If paging is True, wait for Enter between lines.
    If paging is False, print with a small delay (legacy behavior).
    Skips blank lines automatically.
    """
    if paging:
        for ln in lines:
            if ln.strip() == "":
                # skip blank lines silently
                continue
            print(ln)
            wait_for_advance()
    else:
        for ln in lines:
            if ln.strip() == "":
                continue
            print(ln)
            time.sleep(delay)

# ---------- Your SCENES dict (unchanged) ----------
SCENES = {
    "start": {
        "narration": [
            "M: Finally awake, huh?",
            "P:",
            "  1. neutral  [Remain silent]",
            "  2. anger    [Who are you?]",
            "  3. fear     [What happened?]",
            "  4. curiosity[Is this… a dream?]"
        ],
        "choices": [
            {"label":"Remain silent (neutral)", "text":"Remain silent", "next":"what_do_you_want"},
            {"label":"Who are you? (anger)", "text":"Who are you?", "next":"what_do_you_want"},
            {"label":"What happened? (fear)", "text":"What happened?", "next":"what_do_you_want"},
            {"label":"Is this… a dream? (curiosity)", "text":"Is this a dream?", "next":"what_do_you_want"},
        ]
    },

    "what_do_you_want": {
        "narration": [
            "P: what do you want from me?",
            "M: Well, not the time for chitchat. meet me at the shop. *Leaves the room*",
            "P: (inner dialogue) What is this place? Who was that guy?",
            "P: Wait... Who even am I?",
            "P: I should probably follow my only current lead.",
            "Narration: It's raining outside, tight alleyways dimly lit by the moon, nobody to be found.",
            "Narration: You see a light not so far away. You decide to head for it",
            "Narration: Under the light hangs a sign. Jagged, chipped, worn down, barely reads \"Memories\"",
            "Narration: You feel uneasy, but decide to go in anyways. You will do anything to remember... Remember it all.",
            "Narration: The shop reeks of sawdust, tiny place with a counter and many gemstones.",
            "Narration: The merchant appears before you seemingly out of nowhere, Eyes staring into yours. You decide to break the tension",
            "P: I came here as you requested. Now answer my questions."
        ],
        "choices": [
            {"label":"Say that line (continue)", "text":"I came here as you requested. Now answer my questions.", "next":"merchant_scroll"}
        ]
    },

    "merchant_scroll": {
        "narration":[
            "M: Hasty, are we? (chuckles) I needn't answer you myself… Take a look at this:",
            "Narration: The merchant shows you a scroll with many black dim gemstones scattered inside it. Random at first, but taking a shape the more you stare into it.",
            "M: (whispers) Don't lose yourself now.",
            "Narration: you snap back and look at the merchant.",
            "P: What was that?"
        ],
        "choices":[
            {"label":"What was that? (continue)", "text":"What was that?", "next":"first_memory"}
        ]
    },

    "first_memory": {
        "narration":[
            "M: Full of questions you are. Here, you will like this.",
            "Narration: The merchant takes out one of the gems on the scroll and hands it to you.",
            "M: Hold onto it tight and close your eyes...",
            "Narration: The merchant closes your grip onto the gemstone while closing your eye lids with his other hand",
            "Narration: You don't feel the urge to resist. It is pleasant.",
            "Narration: You are suddenly teleported into this alternate reality.",
            "Narration: You are in a warm house, sunlight spilled through the kitchen's window as soft beams filtered through the glass, casting a gentle glow.",
            "Narration: you see a woman cooking. She kneels down; food is almost done.",
            "Narration: with a lovely smile she says \"hey, dear Alaric\" while patting your head.",
            "Narration: You snap back to the rotten shop. The old merchant in front of you, staring you in the eyes.",
            "Narration: You get creeped out and take a strong step back.",
            "Narration: the black gemstone in your hand is now glowing with a pink color.",
            "M: Oh, and that's how you react. (pitiful laughter making fun of you)",
            "M: (whispers) Do you want more?",
            "P:"
        ],
        "choices":[
            {"label":"Yes. I need to remember—whatever it costs. (Vulnerable, curious)", "text":"Yes. I need to remember—whatever it costs.", "next":"after_first_memory"},
            {"label":"You think I’m scared? Bring it on. (Anger)", "text":"You think I’m scared? Bring it on.", "next":"after_first_memory"},
            {"label":"How do I know any of this is real? (Cautious)", "text":"How do I know any of this is real?", "next":"after_first_memory"},
            {"label":"And what if these memories aren’t even mine? (Paranoid)", "text":"And what if these memories aren't even mine?", "next":"after_first_memory"},
            {"label":"Why would I want more? (Cold, neutral)", "text":"Why would I want more?", "next":"after_first_memory"},
        ]
    },

    "after_first_memory": {
        "narration":[
            "M: That's you, and that's your mother. and that pink gemstone is love, your pure mother's love.",
            "M: First one's on the house.",
            "P: (to himself) Considering that this swine is to be trusted, I at least know now my name.",
            "P: I need to know more. I have to make him show me all my memories",
            "M: Spaced out? Guess that was too much (laugh)",
            "Narration: You feel aggravated, challenged",
            "P: Not at all, show me more of your tricks.",
            "M: Oh, but nothing is free in this world dear.",
            "M: For each memory you wish to see, you must sacrifice a part of your body.",
            "P: Whatever do you mean by that?",
            "M: It's simple. Once you go in and come back out, you'll be missing a finger or two (chuckles) until you lose all of yourself."
        ],
        "choices":[
            {"label":"If that’s the price… then take what you must. (Vulnerable, curious)", "text":"If that’s the price… then take what you must.", "next":"gem2"},
            {"label":"Touch me and I break your damn shop. (Anger)", "text":"Touch me and I break your damn shop.", "next":"gem2"},
            {"label":"There’s a workaround, isn’t there? I’ll find it. (Cautious)", "text":"There’s a workaround, isn’t there? I’ll find it.", "next":"gem2"},
            {"label":"I don’t like this… but I need answers. (Paranoid)", "text":"I don’t like this… but I need answers.", "next":"gem2"},
            {"label":"Fine, I will play your little game. (Cold, neutral)", "text":"Fine, I will play your little game.", "next":"gem2"},
        ]
    },

    "gem2": {
        "narration":[
            "Narration: The merchant pulls out another black gemstone from the scroll. Putting it in your hands.",
            "Narration: you wonder which emotion you will experience now.",
            "Narration: Before the merchant closes your grip or eyes, you do it yourself. You know the game now.",
            "M: (voice fading away) ... This one... goes deeper.",
            "Narration: You get teleported to another place. Same House as the first memory. But it feels different.",
            "Narration: you are sitting on the floor of the living room next to a red headed boy who looks like he is the same age as you. you are surrounded by scattered toy pieces and half-built inventions—batteries, plastic gears, you are holding a screwdriver slightly big for your hands, and you both are laughing softly.",
            "Narration: Then, it started.",
            "Narration: Muffled at first—a sharp voice breaking the quiet, then another voice rising to meet it.",
            "Narration: You hear your mother and a man argue. The words blurred into something jagged and fast.",
            "Narration: your friend froze, mid-motion, He glanced at you, instinctively, with concerned looks not knowing what to do, but you were quiet as a dear, you didn’t flinch. Didn’t speak, like it was no surprise, you are used to it, your eyes fix at your hand as you twist the screwdriver too tightly.",
            "Narration: your friend was about to say something, asking if you were okay but he's interrupted by a striking sound, a slap followed by screams from your mother.",
            "Narration: you get up instantly, anger building up inside you, you don't have control over your body, like you're watching a movie.",
            "Narration: you run upstairs only to find the man approaching your mother again while she screams, and without thinking, you lunge at the man and stab him with the screwdriver you realize you were still holding. your mother screams and so do you.",
            "Narration: Looking at your mother to apologize, you see your friend standing at the door, he has seen it all.",
            "Narration: You feel uneasy, panicking, you drop the screwdriver on the floor, somehow you are relieved to have saved your mother, she does not react, and your friend is staring at the man.",
            "Narration: The cops instantly come in, abnormally too quick of a response time. You were about to speak until your friend instantly takes the blame for you, holding the screwdriver, he is Claiming that he did it.",
            "Narration: your eyes met his and he smiles, reassuringly whispering \"it's okay\"",
            "Narration: You snap back to the shop, The smell doesn't bother you anymore, you're used to it. the gemstone glows with a blue light in your hand.",
            "P: What did you just show me? who is this boy, and I would never hurt someone."
        ],
        "choices":[
            {"label":"He saved me… That means something. (compassion)", "text":"He saved me… That means something.", "next":"after_gem2"},
            {"label":"He shouldn't have made such a sacrifice. (anger, guilt)", "text":"He shouldn't have made such a sacrifice.", "next":"after_gem2"},
            {"label":"It's irrelevant. (neutral)", "text":"It's irrelevant.", "next":"after_gem2"},
        ]
    },

    "after_gem2": {
        "narration":[
            "M: this was your childhood best friend, you have caused him a great harm.",
            "P: but why? why did this happen?",
            "M: those questions are not important now; the past is already long gone. the important question is what are you going to do about it now?",
            "P: is there really anything I can do about it? I don't even know where am I.",
            "M: don't be so impulsive, pay close attention to the details and you might know your answers soon enough.",
            "P: (to himself) apparently, the colors of the gemstones are based on emotions, the first one was love, this one must be sadness, maybe if I had more focus, I might be able to know the emotion before the memory ends, and I might know how to influence it.",
            "P: okay, give me the next memory.",
            "M: Shall we proceed?",
            "P: We shall..."
        ],
        "choices":[
            {"label":"Proceed (continue)", "text":"Proceed", "next":"gem3"}
        ]
    },

    "gem3": {
        "narration":[
            "Narration: The air grows thicker. The candlelight in the shop flickers violently, though there's no wind. The gemstones on the scroll seem to shimmer with anticipation—as if alive.",
            "M: Brave. Or foolish. Hard to tell with your kind.",
            "Narration: The merchant extends a hand, slower this time. As if testing the boundaries of your strange new agreement. You reach out, and he places a third gem into your palm.",
            "Narration: you notice you are missing finger, but you are not surprised, you agreed on this game's rules.",
            "Narration: Without a word, you close your hand and shut your eyes. and the world turns inside out.",
            "Narration: it is hot, you're sweating, standing before a board hanging on a wall in a school hall, papers pinned to that board in that familiar, slightly crumpled grid.",
            "Narration: you are surrounded by some high school kids—seemingly your classmates, around the wall, pointing, groaning, cheering.",
            "Narration: you notice an orbit of students clustered around someone. Laughing, talking, voices overlapping as if everyone was trying to be heard just a little more clearly by the one in the center. that boy was the only who didn't rush to see the list, like he had expected it already, that his name would be on the top.",
            "Narration: He walked up calmly, hands in his sweaters' pockets, scanned the list with a faint smirk that said of course, and nodded once, more to himself than anyone else. People clapped him on the back. And the circle of admiration closed around him once again.",
            "Narration: Your hands are damp, as you move your index finger on the paper. You read the same sentence on the headline again \"the test results\", Your heartbeat was loud—too loud—like it might give you away.",
            "Narration: you are searching for your name.",
            "Narration: you take a deep breath, lifting your eyes up again to see that dark haired boy smiling like it didn’t even matter. And maybe it didn’t—to him. But you feel anxious like it meant a great deal to you.",
            "Narration: you slide your eyes back to the paper, they immediately behold the name next to the second place \"Theo Shaw\" your stomach gave that quiet, familiar drop—not quite disappointment, not quite surprise. Just the same dull ache of being almost, again.",
            "Narration: The paper shifts in your hands... no—melts. The ink begins to run.",
            "Narration: The hallway flickers. That boy’s face—smile still frozen—begins to blur, smudged like a watercolor in the rain. and suddenly you are back into the shop.",
            "Narration: you look at the merchant, and for the first time you take in his red hair that is now glitching, his expressions are unreadable. and the gemstone in your hand now has a yellow glow to it, you wonder which emotion have you witnessed.",
            "P: (to himself) This doesn't feel right. it doesn't look real. That merchant scammed me."
        ],
        "choices":[
            {"label":"You tricked me! This isn’t my memory! (Anger)", "text":"You tricked me! This isn’t my memory!", "next":"reaction_glitch"},
            {"label":"That name… Theo… why does it sound familiar? (Curiosity)", "text":"That name… Theo… why does it sound familiar?", "next":"reaction_glitch"},
            {"label":"Wait... am I even Alaric? (Doubt)", "text":"Wait... am I even Alaric?", "next":"reaction_glitch"},
            {"label":"This isn't my memory. my name is not Theo. (Cold)", "text":"This isn't my memory. my name is not Theo.", "next":"reaction_glitch"},
        ]
    },

    "reaction_glitch": {
        "narration":[
            "Narration: The merchant goes to pick out another gemstone only to find his index finger missing.",
            "Narration: The merchant gets surprised and scared.",
            "Narration: Based on the previous choices ..."
        ],
        "choices":[
            {"label":"Now, give me another one.", "text":"Now, give me another one.", "next":"gem4"}
        ]
    },

    "gem4": {
        "narration":[
            "Narration: The merchant mumbling to himself, gets out the fourth gemstone and hands it to you.",
            "Narration: You grip it and close your eyes.",
            "Narration: The city lights glow. you are sitting with someone side by side, robes half-off, diplomas at your side. A quiet university rooftop at dusk. The graduation ceremony has just ended. you feel heavy, you have no idea what you're going to do now with your life.",
            "Narration: the person sitting next to you is staring at the skyline and trying to start a conversation: \"Hard to believe, huh? That it’s over.\"",
            "Narration: you are half-smiling and you say casually: \"You mean this part. Knowing you, it’s never really over. Just a new beginning.\"",
            "Narration: he smiles back, move his hand through the waves of his dark hair: \"Damn right. And this beginning… it’s big.\" then he pauses, glances sideways at you with a flash of determination in his eyes: \"A Neuro Lab reached out. Full access to their neural interface research. Cutting-edge hardware. Autonomy. They want me to lead a new sub-division.\"",
            "Narration: you feel quietly surprised: \"Of course they do. You were always first in line.\"",
            "Narration: he ignores the tone replying: \"I told them I won’t take it unless you come with me. As my partner.\"",
            "Narration: you turn to him, stunned: \"What?\" and he answers: \"Lab partner. Co-lead. We build it together—whatever “it” becomes. You and me. Like it’s always been.\"",
            "Narration: a weird feeling slips into your heart, you say softly: \"Alaric, you don’t need me for that. You never did.\"",
            "Narration: Alaric is suddenly serious: \"That’s where you’re wrong. I’ve got the vision, sure. But you see the things I miss. The patterns, the ethical pitfalls, the consequences. I push forward. You anchor me. We’re not balanced without each other.\"",
            "Narration: ... (summarized) ... you are transported back to the old shop; you are frustrated now. and the gemstone glows in a sharp green color.",
            "P: this isn’t real, how am I witnessing a memory that I’m also talking to me in? this can't be me memory either. and I still can't decode the emotions or the ideas behind them"
        ],
        "choices":[
            {"label":"Am I… watching myself? (Confusion)", "text":"Am I watching myself?", "next":"lab_memory"},
            {"label":"None of this adds up! (Anger)", "text":"None of this adds up!", "next":"lab_memory"},
            {"label":"Even if it’s not mine… maybe it still matters. (Curiosity)", "text":"Even if it’s not mine… maybe it still matters.", "next":"lab_memory"},
            {"label":"Then who am I if none of this is mine? (Doubt)", "text":"Then who am I if none of this is mine?", "next":"lab_memory"},
        ]
    },

    "lab_memory": {
        "narration":[
            "M: I don't know what's wrong, you are right, this is not your memory, this is Theo's memory.",
            "P: who is Theo?",
            "M: Memories are the architects of our identity. you know Theo just like you know yourself. he is a part of you.",
            "(these aren’t choices, these are scene continuation lines)",
            "Based on the previous choices ...",
            "P: what about the gem colors, why do they keep changing?",
            "M: Emotions are the colors of the soul, and you have lost your soul, Alaric.",
            "M: you should try to get it back, Hold onto your memories and your emotions. the stronger emotions are the ones that affect you the most and you can affect them as well.",
            "M: this memory held the joy, the excitement of accepting a friend's offer. it may not be your memory, but it certainly gave you something to learn.",
            "(these aren’t choices, these are scene continuation lines)",
            "Based on the previous choices ..."
        ],
        "choices":[
            {"label":"I can't tolerate any more false memories, give me a right one.", "text":"I can't tolerate any more false memories, give me a right one.", "next":"gem5"},
            {"label":"Stop speaking in riddles. I want facts.", "text":"Stop speaking in riddles. I want facts.", "next":"gem5"},
            {"label":"Then I’ll find every color, and reclaim what I was.", "text":"Then I’ll find every color, and reclaim what I was.", "next":"gem5"},
            {"label":"Or maybe you're just assigning color to keep me guessing.", "text":"Or maybe you're just assigning color to keep me guessing.", "next":"gem5"},
        ]
    },

    "gem5": {
        "narration":[
            "M: here, take this.",
            "Narration: he takes out the fifth gemstone and place it in your hand, you notice his hand missing another finger, but he doesn't seem to care. the gemstone now feels warm against your palm.",
            "(these aren’t choices, these are scene continuation lines)",
            "Narration: The shop starts to shift—walls stretch, the counter melts into the floor, and the merchant’s form flickers, and you find yourself in a different place.",
            "Narration: you find yourself in a lab, silent as you hear your footsteps, you are restless, walking back and forth. it is late night, Rain tapping against the high lab windows...",
            "Narration: In the center: The device, Glowing. finally ready, finally alive.",
            "Narration: you stare at it and whisper: \"The Cerebridge.\"",
            "Narration: ... (long lab sequence omitted for brevity in print) ...",
            "Narration: you open your eyes and suddenly you are in the shop again, the gemstone glows with a purple color, you look at the merchant again and now you know, the merchant is Theo.",
            "P: it's you! you are him! you are a part of my past! i saw you!"
        ],
        "choices":[
            {"label":"This is manipulation. You’ve been twisting my mind! (Anger)", "text":"This is manipulation. You’ve been twisting my mind!", "next":"final_branch"},
            {"label":"How can that be? Why would I see your life like it’s mine? (Confusion)", "text":"How can that be? Why would I see your life like it’s mine?", "next":"final_branch"},
            {"label":"So, the Cerebridge created cross-memory resonance... (Cold, neutral)", "text":"So, the Cerebridge created cross-memory resonance...", "next":"final_branch"},
            {"label":"Theo... I remember now. It wasn’t just your life. It was ours. (Empathy)", "text":"Theo... I remember now. It wasn’t just your life. It was ours.", "next":"final_branch"},
        ]
    },

    "final_branch": {
        "narration":[
            "P: but how is this possible? how did I have access to your memories as well as mine?",
            "M: you know the answer to that, you invented it yourself.",
            "P: (to himself) the cerebridge device…",
            "P: I am in your head!",
            "M: you're close enough. you were in my head, but now i am in yours.",
            "P: I don't believe you. I can't believe you.",
            "M: Then go. Find one more. Let the truth carve what’s left of you.",
            "Narration: You stare down at your hands. They tremble. One more gem sits before you, unclaimed. Unlike the others, it glows before you touch it. the merchant's fingers came back as he handles you the last gemstone.",
            "P (to himself) One more... and I either find who I am—or lose it all.",
            "Narration: You pick it up. And for the first time—you don’t close your eyes.",
            "Narration: ... (final lab / Cerebridge sequence) ...",
            "Narration: You jolt back into the shop, gasping. But something is wrong. The shop is different—brighter. No sawdust. The gemstones are gone. Only the scroll remains, and it’s... blank.",
            "M: (calmly) You reached the boundary.",
            "P: What boundary",
            "M: Between remembering... and becoming.",
            "P: Becoming what",
            "M: A fragment. A story. A soul trapped in recollection.",
            "P: This isn't memory... it's madness.",
            "M: Memory is madness, if seen too clearly. That's why we forget.",
            "P: I won't accept this memory, i have to go back.",
            "Narration: you press the same gemstone in your hand strongly, it is glowing bright red, you figure out that this is your core memory, your most strong emotion... regret.",
            "Narration: you know what to do now."
        ],
        "choices":[
            {"label":"Vulnerability (proceed)", "text":"Because it hurt too much.", "next":"end_vulnerable"},
            {"label":"Anger, guilt (game over)", "text":"Because I had to move on.", "next":"end_gameover"},
            {"label":"Cold, neutral (proceed)", "text":"I didn’t think it mattered.", "next":"end_vulnerable"},
            {"label":"Empathy (game over)", "text":"I didn't want to abandon my invention.", "next":"end_gameover"},
        ]
    },

    "end_vulnerable": {
        "narration":[
            "Narration: It is the same lab. Midnight. The machine still hums softly; the screens dim and patient. Nothing has changed, and yet... everything feels different.",
            "Narration: You kneel beside Theo. You choose compassion. The shop fades. You wake up in the lab. Theo is alive. You changed the past.",
            "M: You have what you came for. you can Leave now. you freed yourself from the guilt that trapped you in your head.",
            "P: How? You said that nothing is free.",
            "M: It isn’t.",
            "Narration: the merchant's body starts to fade away.",
            "M: (whispers) you freed me too...",
            "Narration: You look down. Your hands—both whole. But your reflection in the gem's surface is... not. Hollow eyes. Mouth sewn shut. but you feel relieved.",
            "Narration: you hear a distant voice, low, but sharp.",
            "\"Wake up, Alaric! You have to wake up! now!\"",
            "Narration: you open your eyes slowly, you are in the lab, sleeping on the chair, Theo is next to you, glancing at you, with real concern in his eyes, he says: \"oh, thank god, you are okay!\"",
            "Narration: GAME OVER (but you freed something)."
        ],
        "choices":[]
    },

    "end_gameover": {
        "narration":[
            "Narration: Things rip apart. You are trapped. GAME OVER."
        ],
        "choices":[]
    }
}
# ---------- Helpers for detecting numbered blocks ----------
_numbered_line_pattern = re.compile(r"^\s*(\d+)\.\s*(.*)$")

def is_single_line_choice(line: str) -> bool:
    """Detect a single line containing at least two numbered options like '1.' and '2.'."""
    return bool(re.search(r"\b1\.", line)) and bool(re.search(r"\b2\.", line))

def collect_numbered_block(narration_lines, start_index):
    """
    Return (block_lines, end_index, options)
    options: list of (num_str, text)
    """
    n = len(narration_lines)
    cur = narration_lines[start_index]
    # Case A: single line containing multiple "1. ... 2. ..." entries
    if is_single_line_choice(cur):
        pattern = re.compile(r'(\d+)\.\s*(.*?)(?=(?:\s+\d+\.|$))')
        found = pattern.findall(cur)
        options = [(num, text.strip()) for num, text in found]
        return [cur], start_index + 1, options

    # Case B: "P:" line followed by numbered option lines
    if 'P:' in cur or 'p:' in cur:
        j = start_index + 1
        numbered_lines = []
        while j < n and _numbered_line_pattern.match(narration_lines[j]):
            numbered_lines.append(narration_lines[j])
            j += 1
        if numbered_lines:
            opts = []
            for ln in numbered_lines:
                m = _numbered_line_pattern.match(ln)
                if m:
                    opts.append((m.group(1), m.group(2).rstrip()))
            return [cur] + numbered_lines, j, opts

    # Case C: block of numbered lines without preceding P:
    if _numbered_line_pattern.match(cur):
        j = start_index
        numbered_lines = []
        while j < n and _numbered_line_pattern.match(narration_lines[j]):
            numbered_lines.append(narration_lines[j])
            j += 1
        if len(numbered_lines) >= 2:
            opts = []
            for ln in numbered_lines:
                m = _numbered_line_pattern.match(ln)
                if m:
                    opts.append((m.group(1), m.group(2).rstrip()))
            return numbered_lines, j, opts

    return None, start_index, None

def prompt_numeric_choice_inline(options):
    """
    Prompt user to pick a numeric option from a block of options.
    Returns the chosen number string.
    """
    valid_nums = {num for num, _ in options}
    opts_sorted = sorted(valid_nums, key=lambda x: int(x))
    while True:
        try:
            sel = input(f"Choose an option {opts_sorted} (type the number): ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nExiting.")
            sys.exit(0)
        if sel in valid_nums:
            return sel
        print("Invalid choice. Please type one of the option numbers shown (e.g. 1, 2...).")

def present_scene(scene_id):
    scene = SCENES.get(scene_id)
    if not scene:
        print(f"[!] Missing scene: {scene_id}")
        return None
    print("\n" + "="*70)

    narration = scene.get("narration", [])
    i = 0
    while i < len(narration):
        ln = narration[i]
        if ln.strip() == "":
            i += 1
            continue

        # Single-line inline block e.g. "P: 1. Say nothing 2. Who are you?"
        if is_single_line_choice(ln):
            print(ln)
            block_lines, next_index, options = collect_numbered_block(narration, i)
            sel = prompt_numeric_choice_inline(options)
            chosen_text = next((t for n, t in options if n == sel), "")
            print(f"You chose: {sel}. {chosen_text}")

            # Map to the scene-level choices if available (so user doesn't need to pick twice)
            scene_choices = scene.get("choices", [])
            try:
                idx = int(sel) - 1
                if 0 <= idx < len(scene_choices):
                    return scene_choices[idx]
            except Exception:
                pass
            # If no matching scene-level mapping, return an ad-hoc choice dict
            return {"label": chosen_text, "text": chosen_text, "next": None}

        # Multi-line block: P: then numbered lines, or several numbered lines in a row
        block_lines, next_index, options = collect_numbered_block(narration, i)
        if block_lines:
            # Print the whole block as-is
            for b in block_lines:
                print(b)
            sel = prompt_numeric_choice_inline(options)
            chosen_text = next((t for n, t in options if n == sel), "")
            print(f"You chose: {sel}. {chosen_text}")

            # Map to scene-level choices if exists
            scene_choices = scene.get("choices", [])
            try:
                idx = int(sel) - 1
                if 0 <= idx < len(scene_choices):
                    return scene_choices[idx]
            except Exception:
                pass
            return {"label": chosen_text, "text": chosen_text, "next": None}

        # Normal narration line
        print(ln)
        wait_for_advance()
        i += 1

    # If no inline numbered block triggered a return, present the scene-level choices (legacy)
    choices = scene.get("choices", [])
    if not choices:
        return None
    print("\nChoices:")
    for idx, c in enumerate(choices, start=1):
        print(f"  {idx}. {c['label']}")
    print("  0. Quit")
    while True:
        ans = input("\nChoose a number: ").strip()
        if ans == "0":
            print("Exiting.")
            sys.exit(0)
        if not ans.isdigit():
            print("Enter a number.")
            continue
        idx = int(ans) - 1
        if 0 <= idx < len(choices):
            return choices[idx]
        print("Invalid choice.")

def _print_ai_immediate(text):
    """
    Print AI reply immediately, skipping blank lines.
    Used so the player doesn't need to press Enter before seeing the AI reply.
    """
    if text is None:
        return
    lines = text.splitlines()
    for ln in lines:
        if ln.strip() == "":
            continue
        print(ln)

def process_choice(choice):
    player_text = choice["text"]
    # echo player's chosen text to the log/console
    print(f"\n-- You: {player_text}")

    # 1) sentiment
    sentiment = call_sentiment(player_text)
    if sentiment:
        print(f"[Sentiment] {sentiment.get('label')} (conf={sentiment.get('confidence')})")
    else:
        print("[Sentiment] unavailable - proceeding")

    # 2) call AI
    ai_json = call_ai(player_text, sentiment=sentiment, history=state["history"])
    if ai_json:
        ai_text = ai_json.get("ai_response") or ai_json.get("response") or ai_json.get("text") or "<no response>"
        # Print the AI-generated merchant reply immediately (no paging before it)
        print("\n--- Merchant replies: ---")
        _print_ai_immediate(ai_text)
        print("-------------------------")
        # record history
        state["history"].append({"player": player_text, "sentiment": sentiment, "ai": ai_text})
    else:
        print("\n[Merchant reply unavailable. Proceeding without merchant dynamic reply.]")
        state["history"].append({"player": player_text, "sentiment": sentiment, "ai": None})

    # Now pause once so the player must press Enter to continue to the next narration.
    # This ensures: choose (Enter) -> see AI reply -> press Enter -> next narration.
    wait_for_advance()

def main():
    print("=== MEMORY MERCHANT — CLI ===")
    print("(Press Enter to advance narration lines. Numbered choice blocks in narration accept numeric input and advance immediately.)")
    cur = "start"
    while cur:
        chosen = present_scene(cur)
        if chosen is None:
            print("\n=== THE END ===")
            break
        # process_choice will call sentiment + AI and print merchant reply immediately
        process_choice(chosen)
        nxt = chosen.get("next")
        if not nxt:
            print("[!] No next scene configured. Ending.")
            break
        cur = nxt
    print("\nThank you for playing. Final state summary:")
    print(state)

if __name__ == "__main__":
    main()
